name: Go CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Go tests
        run: go test ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with SHA tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: junaidkhan126072/go-ci-cd-demo:${{ github.sha }}

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

      - name: Update Kubernetes deployment with new image
        run: |
          kubectl set image deployment/go-deployment go-container=junaidkhan126072/go-ci-cd-demo:${{ github.sha }}
