name: Deploy to Kubernetes

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          # Create the .kube directory if it doesn't exist
          mkdir -p ~/.kube
          # Decode and save kubeconfig to standard location
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
          # Verify file was created
          ls -la ~/.kube/config

      - name: Confirm cluster connection
        run: kubectl cluster-info

      - name: Set kubectl context
        run: |
          kubectl config use-context minikube
          kubectl config get-contexts

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
