name: Deploy to Kubernetes

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

      - name: Confirm cluster connection
        run: |
          kubectl cluster-info

      - name: Set kubectl context
        run: |
          kubectl config get-contexts
          kubectl config use-context minikube

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
