name: Deploy to Kubernetes

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Kubernetes configuration
        run: |
          # Decode the kubeconfig secret and save to a file
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig.yaml

          # Verify file was created
          echo "Kubeconfig file created:"
          ls -l kubeconfig.yaml
          echo "First 100 characters of kubeconfig:"
          head -c 100 kubeconfig.yaml

          # Set environment variable for subsequent steps
          echo "KUBECONFIG=$PWD/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Verify cluster access
        run: |
          # Check config and cluster connection
          echo "Current KUBECONFIG: $KUBECONFIG"
          kubectl config view
          kubectl cluster-info
          kubectl get nodes

      - name: Set Kubernetes context
        run: |
          kubectl config use-context minikube
          kubectl config current-context

      - name: Deploy application
        run: |
          echo "Deploying manifests from k8s/ directory"
          kubectl apply -f k8s/ --validate=true
          echo "Deployment status:"
          kubectl get deployments,services,pods --all-namespaces

      - name: Verify deployment
        run: |
          # Add verification logic specific to your application
          echo "Verifying deployment..."
          kubectl rollout status deployment/<your-deployment-name> --timeout=2m
          # Add any additional checks here
