name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Set kubectl context
        run: |
          kubectl config get-contexts
          kubectl config use-context minikube

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
