name: Deploy to Kubernetes

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubeconfig in /tmp
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > /tmp/kubeconfig

      - name: Confirm cluster connection
        run: |
          kubectl --kubeconfig=/tmp/kubeconfig cluster-info

      - name: Set kubectl context
        run: |
          kubectl --kubeconfig=/tmp/kubeconfig config use-context minikube || true
          kubectl --kubeconfig=/tmp/kubeconfig config get-contexts

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=/tmp/kubeconfig apply -f k8s/
